CREATE TABLE IF NOT EXISTS roles (id INT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50) UNIQUE);
INSERT IGNORE INTO roles (id,name) VALUES (1,'admin'),(2,'user'),(3,'moderator');

CREATE TABLE IF NOT EXISTS users (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  role_id INT DEFAULT 2,
  email VARCHAR(190) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  name VARCHAR(120) NOT NULL,
  avatar VARCHAR(255) NULL,
  banner VARCHAR(255) NULL,
  bio TEXT NULL,
  theme VARCHAR(30) DEFAULT 'netflix',
  twofa_enabled TINYINT(1) DEFAULT 0,
  email_verified TINYINT(1) DEFAULT 0,
  created_at DATETIME NOT NULL,
  INDEX(role_id)
);
CREATE TABLE IF NOT EXISTS profiles (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL, name VARCHAR(100), is_kid TINYINT(1) DEFAULT 0, pin_hash VARCHAR(255), privacy_public TINYINT(1) DEFAULT 1, created_at DATETIME, INDEX(user_id));
CREATE TABLE IF NOT EXISTS sessions (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, token CHAR(64), device VARCHAR(120), ip VARCHAR(64), last_seen DATETIME, INDEX(user_id));
CREATE TABLE IF NOT EXISTS movies (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255));
CREATE TABLE IF NOT EXISTS series (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255));
CREATE TABLE IF NOT EXISTS seasons (id BIGINT AUTO_INCREMENT PRIMARY KEY, series_id BIGINT, season_number INT, title VARCHAR(255), INDEX(series_id));
CREATE TABLE IF NOT EXISTS episodes (id BIGINT AUTO_INCREMENT PRIMARY KEY, season_id BIGINT, episode_number INT, title VARCHAR(255), INDEX(season_id));
CREATE TABLE IF NOT EXISTS shorts (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255));
CREATE TABLE IF NOT EXISTS extras (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255));
CREATE TABLE IF NOT EXISTS catalog_items (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tmdb_id BIGINT UNIQUE,
  content_type VARCHAR(20) NOT NULL,
  title VARCHAR(255) NOT NULL,
  original_title VARCHAR(255) NULL,
  synopsis TEXT NULL,
  year INT NULL,
  duration INT NULL,
  age_rating VARCHAR(20) NULL,
  country VARCHAR(100) NULL,
  language VARCHAR(20) NULL,
  cast_names TEXT NULL,
  director VARCHAR(255) NULL,
  tags TEXT NULL,
  poster VARCHAR(255) NULL,
  banner VARCHAR(255) NULL,
  thumbnail VARCHAR(255) NULL,
  trailer_url VARCHAR(255) NULL,
  status VARCHAR(20) DEFAULT 'draft',
  slug VARCHAR(255) NULL,
  meta_title VARCHAR(255) NULL,
  meta_description TEXT NULL,
  price_tokens INT DEFAULT 0,
  access_mode VARCHAR(20) DEFAULT 'free',
  published_at DATETIME NULL
);
CREATE TABLE IF NOT EXISTS media_sources (id BIGINT AUTO_INCREMENT PRIMARY KEY, item_id BIGINT, source_order INT, url VARCHAR(500), format VARCHAR(20), INDEX(item_id));
CREATE TABLE IF NOT EXISTS subtitles (id BIGINT AUTO_INCREMENT PRIMARY KEY, item_id BIGINT, lang VARCHAR(20), file_url VARCHAR(255), INDEX(item_id));
CREATE TABLE IF NOT EXISTS trailers (id BIGINT AUTO_INCREMENT PRIMARY KEY, item_id BIGINT, url VARCHAR(255), provider VARCHAR(50), INDEX(item_id));
CREATE TABLE IF NOT EXISTS tmdb_cache (id BIGINT AUTO_INCREMENT PRIMARY KEY, cache_key VARCHAR(190) UNIQUE, payload LONGTEXT, expires_at DATETIME);
CREATE TABLE IF NOT EXISTS import_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, tmdb_id BIGINT, content_type VARCHAR(20), action VARCHAR(30), created_at DATETIME);
CREATE TABLE IF NOT EXISTS token_packages (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), token_amount INT, price DECIMAL(10,2), active TINYINT(1) DEFAULT 1);
CREATE TABLE IF NOT EXISTS token_wallets (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNIQUE, balance INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS token_transactions (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, amount INT, type VARCHAR(20), description VARCHAR(255), created_at DATETIME, INDEX(user_id));
CREATE TABLE IF NOT EXISTS unlocks (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, item_id BIGINT, expires_at DATETIME NULL, created_at DATETIME, INDEX(user_id), INDEX(item_id));
CREATE TABLE IF NOT EXISTS coupons (id BIGINT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(60) UNIQUE, discount_percent INT, active TINYINT(1), expires_at DATETIME);
CREATE TABLE IF NOT EXISTS promotions (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), bonus_percent INT, starts_at DATETIME, ends_at DATETIME);
CREATE TABLE IF NOT EXISTS subscription_plans (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100), period_months INT, price DECIMAL(10,2), screens INT);
CREATE TABLE IF NOT EXISTS subscriptions (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, plan_id BIGINT, status VARCHAR(20), starts_at DATETIME, ends_at DATETIME, INDEX(user_id));
CREATE TABLE IF NOT EXISTS watch_history (id BIGINT AUTO_INCREMENT PRIMARY KEY, profile_id BIGINT, item_id BIGINT, watched_minutes INT, watched_at DATETIME, INDEX(profile_id));
CREATE TABLE IF NOT EXISTS continue_watching (id BIGINT AUTO_INCREMENT PRIMARY KEY, profile_id BIGINT, item_id BIGINT, progress_seconds INT, updated_at DATETIME, UNIQUE KEY(profile_id,item_id));
CREATE TABLE IF NOT EXISTS favorites (id BIGINT AUTO_INCREMENT PRIMARY KEY, profile_id BIGINT, item_id BIGINT, created_at DATETIME, UNIQUE KEY(profile_id,item_id));
CREATE TABLE IF NOT EXISTS user_lists (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, name VARCHAR(120), description TEXT, cover VARCHAR(255), is_public TINYINT(1), created_at DATETIME);
CREATE TABLE IF NOT EXISTS list_items (id BIGINT AUTO_INCREMENT PRIMARY KEY, list_id BIGINT, item_id BIGINT, created_at DATETIME, UNIQUE KEY(list_id,item_id));
CREATE TABLE IF NOT EXISTS ratings (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, item_id BIGINT, stars TINYINT, liked TINYINT(1), created_at DATETIME, UNIQUE KEY(user_id,item_id));
CREATE TABLE IF NOT EXISTS comments (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, item_id BIGINT, body TEXT, status VARCHAR(20), created_at DATETIME);
CREATE TABLE IF NOT EXISTS comment_replies (id BIGINT AUTO_INCREMENT PRIMARY KEY, comment_id BIGINT, user_id BIGINT, body TEXT, created_at DATETIME);
CREATE TABLE IF NOT EXISTS reactions (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, target_type VARCHAR(30), target_id BIGINT, reaction VARCHAR(30), created_at DATETIME);
CREATE TABLE IF NOT EXISTS reports (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, target_type VARCHAR(30), target_id BIGINT, reason TEXT, status VARCHAR(20), created_at DATETIME);
CREATE TABLE IF NOT EXISTS forum_categories (id BIGINT AUTO_INCREMENT PRIMARY KEY, parent_id BIGINT NULL, title VARCHAR(120), slug VARCHAR(140), sort_order INT DEFAULT 0);
CREATE TABLE IF NOT EXISTS forum_topics (id BIGINT AUTO_INCREMENT PRIMARY KEY, category_id BIGINT, user_id BIGINT, title VARCHAR(255), is_pinned TINYINT(1), is_locked TINYINT(1), status VARCHAR(20), created_at DATETIME);
CREATE TABLE IF NOT EXISTS forum_posts (id BIGINT AUTO_INCREMENT PRIMARY KEY, topic_id BIGINT, user_id BIGINT, body TEXT, created_at DATETIME);
CREATE TABLE IF NOT EXISTS forum_tags (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(60) UNIQUE, slug VARCHAR(70));
CREATE TABLE IF NOT EXISTS forum_likes (id BIGINT AUTO_INCREMENT PRIMARY KEY, post_id BIGINT, user_id BIGINT, created_at DATETIME, UNIQUE KEY(post_id,user_id));
CREATE TABLE IF NOT EXISTS chat_rooms (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120), is_group TINYINT(1), created_by BIGINT, created_at DATETIME);
CREATE TABLE IF NOT EXISTS chat_members (id BIGINT AUTO_INCREMENT PRIMARY KEY, room_id BIGINT, user_id BIGINT, joined_at DATETIME, UNIQUE KEY(room_id,user_id));
CREATE TABLE IF NOT EXISTS chat_messages (id BIGINT AUTO_INCREMENT PRIMARY KEY, room_id BIGINT, user_id BIGINT, message TEXT, attachment VARCHAR(255), created_at DATETIME);
CREATE TABLE IF NOT EXISTS chat_blocks (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, blocked_user_id BIGINT, created_at DATETIME, UNIQUE KEY(user_id,blocked_user_id));
CREATE TABLE IF NOT EXISTS chat_reports (id BIGINT AUTO_INCREMENT PRIMARY KEY, reporter_id BIGINT, message_id BIGINT, reason TEXT, created_at DATETIME);
CREATE TABLE IF NOT EXISTS notifications (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NULL, title VARCHAR(255), body TEXT, type VARCHAR(40), created_at DATETIME);
CREATE TABLE IF NOT EXISTS notification_reads (id BIGINT AUTO_INCREMENT PRIMARY KEY, notification_id BIGINT, user_id BIGINT, read_at DATETIME, UNIQUE KEY(notification_id,user_id));
CREATE TABLE IF NOT EXISTS notification_preferences (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, pref_key VARCHAR(80), enabled TINYINT(1), UNIQUE KEY(user_id,pref_key));
CREATE TABLE IF NOT EXISTS settings (`key` VARCHAR(120) PRIMARY KEY, `value` TEXT);
CREATE TABLE IF NOT EXISTS themes (id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(50), css_file VARCHAR(120), is_active TINYINT(1));
CREATE TABLE IF NOT EXISTS admin_audit_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, admin_id BIGINT, action VARCHAR(255), metadata JSON NULL, created_at DATETIME);
CREATE TABLE IF NOT EXISTS error_logs (id BIGINT AUTO_INCREMENT PRIMARY KEY, level VARCHAR(20), message TEXT, context JSON NULL, created_at DATETIME);
CREATE TABLE IF NOT EXISTS maintenance_flags (id BIGINT AUTO_INCREMENT PRIMARY KEY, enabled TINYINT(1), message VARCHAR(255), updated_at DATETIME);
CREATE TABLE IF NOT EXISTS support_tickets (id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT, subject VARCHAR(255), status VARCHAR(30), created_at DATETIME);
CREATE TABLE IF NOT EXISTS support_messages (id BIGINT AUTO_INCREMENT PRIMARY KEY, ticket_id BIGINT, user_id BIGINT, message TEXT, created_at DATETIME);
